name = "BoundingBoxes"
uuid = "e33dfbef-2ea3-5ef3-a604-7da28c17a6d4"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com>"]
version = "0.1.1"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
